models/alert.py
from dataclasses import dataclass, field
from typing import Dict
import uuid
from libs.mailgun import Mailgun
from models.item import Item
from models.model import Model
from models.user.user import User


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: str
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "price_limit": self.price_limit,
            "item_id": self.item._id,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        if self.item.price < self.price_limit:
            print(f"Item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}.")

            Mailgun.send_mail(
                [self.user_email],
                f'Notification for {self.name}',
                f'Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.',
                f'<p>Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}.</p><p> Go to this address to check your item: {self.item.url}.</p>',



            )

src/models/alert.py
from dataclasses import dataclass, field
from typing import Dict
import uuid
from src.libs.mailgun import Mailgun
from src.models.item import Item
from src.models.model import Model
from src.models.user.user import User


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: str
    user_email: str
    _id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "price_limit": self.price_limit,
            "item_id": self.item._id,
            "user_email": self.user_email
        }

    def load_item_price(self) -> float:
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self) -> None:
        if self.item.price < self.price_limit:
            print(f"Item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}.")

            Mailgun.send_mail(
                [self.user_email],
                f'Notification for {self.name}',
                f'Your alert {self.name} has reached a price under {self.price_limit}. The latest price is {self.item.price}. Go to this address to check your item: {self.item.url}.',
                f'<p>Your alert {self.name} has reached a price under {self.price_limit}.</p><p>The latest price is {self.item.price}.</p><p> Go to this address to check your item: {self.item.url}.</p>',



            )

src/views/alerts.py
from flask import render_template, Blueprint, request, redirect, url_for, session

from src.models.alert import Alert
from src.models.item import Item
from src.models.store import Store
from src.models.user.decorators import requires_login

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@requires_login
def index():
    print(session['email'])
    # alerts = Alert.all()
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['GET','POST'])
@requires_login
def create_alert():
    if request.method == 'POST':
        item_url = request.form['item_url']
        alert_name = request.form['alert_name']
        price_limit = float(request.form['price_limit'])

        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_mongo()


        Alert(alert_name, item._id, price_limit, session['email']).save_to_mongo()

        #return something like item added

    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET','POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method =='POST':
        price_limit = float(request.form['price_limit'])
        alert.price_limit = price_limit
        alert.save_to_mongo()

        #URL FOR CALCULATE THE CURRENT INDEX METHOD "." MEANS CURRENT BLUEPRINT
        return redirect(url_for('.index'))
    return render_template('alerts/edit.html', alert=alert)


@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session['email']:
        alert.remove_from_mongo()

    return redirect(url_for('.index'))

views/alerts.py
from flask import render_template, Blueprint, request, redirect, url_for, session

from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user.decorators import requires_login

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@requires_login
def index():
    print(session['email'])
    # alerts = Alert.all()
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['GET','POST'])
@requires_login
def create_alert():
    if request.method == 'POST':
        item_url = request.form['item_url']
        alert_name = request.form['alert_name']
        price_limit = float(request.form['price_limit'])

        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_mongo()


        Alert(alert_name, item._id, price_limit, session['email']).save_to_mongo()

        #return something like item added

    return render_template('alerts/new_alert.html')

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET','POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method =='POST':
        price_limit = float(request.form['price_limit'])
        alert.price_limit = price_limit
        alert.save_to_mongo()

        #URL FOR CALCULATE THE CURRENT INDEX METHOD "." MEANS CURRENT BLUEPRINT
        return redirect(url_for('.index'))
    return render_template('alerts/edit.html', alert=alert)


@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session['email']:
        alert.remove_from_mongo()

    return redirect(url_for('.index'))

templates/alerts/edit.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Update Alert</h1></header>
    <section class="update-alert-form">
        <form method="post">
            <div class ="form-group">
                <label for="alert_name">Alert name</label>
                <input type="text" class="form-control" id="alert_name" name="alert_name" value="{{ alert.name }}" disabled/>
            </div>
            <div class ="form-group">
                <label for="item_url">URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled/>
            </div>
            <div class ="form-group">
                <label for="price_limit">Price limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" value="{{ alert.price_limit }}"placeholder="$"/>
            </div>
            <button type="submit" class="btn btn-primary">Update alert</button>
        </form>
    </section>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}

<header>
    <h1>Alerts </h1>
</header>

<section>
    <div class="list-group">
        {% for alert in alerts %}
            <div class="list-group-item">
                <h4>{{ alert.name }}</h4>
                <p>
                    <a href="{{ alert.item.url }}">{{ alert.item.url }} </a> - last price {{ alert.item.price }} $.
                </p>
                <p>
                    {{ alert.item._id }}
                </p>
<!--                specify function name inside the blueprint  -->
                <a class="btn btn-secondary" href="{{url_for('alerts.edit_alert', alert_id = alert._id) }} ">
                    Edit
                </a>
                <a class="btn btn-danger" href="{{url_for('alerts.delete_alert', alert_id = alert._id) }} ">
                    Delete
                </a>
            </div>
        {% endfor %}
    </div>
<!--    url_for('items.create_item' == naza blueprintu i potem nazwa metody -->
    <a class="btn btn-primary mt-3" href="{{ url_for('alerts.create_alert') }}">
        Create new alert
    </a>
</section>

{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Alert</h1></header>
    <section class="create-alert-form">
        <form method="post">
            <div class ="form-group">
                <label for="alert_name">Alert name</label>
                <input type="text" class="form-control" id="alert_name" name="alert_name"/>
            </div>
            <div class ="form-group">
                <label for="item_url">URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url"/>
            </div>
            <div class ="form-group">
                <label for="price_limit">Price limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="$"/>
            </div>
            <button type="submit" class="btn btn-primary">Create alert</button>
        </form>
    </section>
{% endblock %}